-- MySQL Script generated by MySQL Workbench
-- Tue Jul  5 08:06:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mytest12
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mytest12
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytest12` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mytest12` ;

-- -----------------------------------------------------
-- Table `mytest12`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytest12`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `sesion` VARCHAR(45) NULL DEFAULT 'false',
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytest12`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytest12`.`publications` (
  `idpublications` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `stamp` VARCHAR(40) NULL DEFAULT NULL,
  `content` VARCHAR(15000) NULL DEFAULT NULL,
  `likes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idpublications`),
  INDEX `FK_Usuario_Author` (`author` ASC) VISIBLE,
  CONSTRAINT `FK_Usuario_Author`
    FOREIGN KEY (`author`)
    REFERENCES `mytest12`.`usuario` (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytest12`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytest12`.`comments` (
  `idcomments` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(200) NULL DEFAULT NULL,
  `stamp` VARCHAR(45) NULL DEFAULT NULL,
  `autorid` INT NULL DEFAULT NULL,
  `postid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idcomments`),
  UNIQUE INDEX `idcomments_UNIQUE` (`idcomments` ASC) VISIBLE,
  INDEX `fk_autor_idx` (`autorid` ASC) VISIBLE,
  INDEX `fk_post_idx` (`postid` ASC) VISIBLE,
  CONSTRAINT `fk_autor`
    FOREIGN KEY (`autorid`)
    REFERENCES `mytest12`.`usuario` (`idusuario`),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`postid`)
    REFERENCES `mytest12`.`publications` (`idpublications`))
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytest12`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytest12`.`profile` (
  `idprofile` INT NOT NULL AUTO_INCREMENT,
  `profile_user` INT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `birthdate` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `job` VARCHAR(45) NULL DEFAULT NULL,
  `picture` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idprofile`),
  UNIQUE INDEX `profile_idprofile` (`profile_user` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_profile`
    FOREIGN KEY (`profile_user`)
    REFERENCES `mytest12`.`usuario` (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
